### ISSUE TITLE
Liquid Exceptions when doing a Jekyll build

### ISSUE THREAD

**Issue by Yohanna** [poole/hyde#114]
I'm getting the following exceptions when doing a `jekyll build`

```
Liquid Exception: Liquid syntax error: Unknown tag 'gist' in /home/yohanna/hyde/_posts/2012-02-07-example-content.md/#excerpt
Liquid Exception: Liquid syntax error: Unknown tag 'gist' in _layouts/post.html
```

Note that deleting the file `2012-02-07-example-content.md` solves the problem. Jekyll can't parse the tag `gist` in line 55 in that file.

**Comment by waldofe** [comment]
@Yohanna Got it working by setting those gems on `_config`:

```
gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
```

**Comment by Yohanna** [comment]
I missed the `jekyll-gist` gem. Thanks @oswaldoferreira
