### ISSUE TITLE
Two level menu in HYDE for HUGO

### ISSUE THREAD

**Issue by a-akram** [poole/hyde#116]
Hello everyone
I am creating a static site with HUGO by using HYDE theme. I wanted to create two level menu (i.e. two level list) on the sidebar. My menu should look like this (you can see it here http://www.dune-project.org/1). I wanted to use Front Matter for menus.  Like parent/children method to create menu.

...
What is DUNE
- Features
- News
- License
- Gallery
- Publications and Talks
- Dune Logo
- Commercial Support
  DUNE modules
- Core modules
- Discretization modules
- Grid managers
- External modules

and so on
...

I am new to HUGO and it is drive me crazy to do this simple task. I will appreciate any kind of help from you guys.

Best Regards
Adeel

**Comment by mdo** [comment]
Sorry, I personally can't help you here. This repo is only for the Hyde theme for Jekyll. Someone else might be able to help, but no guarantees.
