### ISSUE TITLE
Does not work with Jekyll 3

### ISSUE THREAD

**Issue by stsievert** [poole/hyde#118]
When I download the v2.0 or the master branch, cd to the root folder and run `jekyll serve`, I get the following output:

``` shell
$ jekyll serve
Configuration file: /Users/scott/Desktop/hyde/_config.yml
       Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
            Source: /Users/scott/Desktop/hyde
       Destination: /Users/scott/Desktop/hyde/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Since v3.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Check http://jekyllrb.com/docs/upgrading/ for more info.
```

This looks like an issue with the update to Jekyll 3 -- I could make the first warning disappear by adding the required line to `_config.yml`.

**Comment by stsievert** [comment]
Clarification: apparently Jekyll doesn't work with Python 3 (https://github.com/jekyll/jekyll/issues/2604). This issue is closed.

**Comment by anhiliate** [comment]
I know it's a bit late but it will work if you call `jekyll serve --incremental` instead of `jekyll serve`

**Comment by dbhaskaran1** [comment]
I'm still seeing this error, even with --incremental.

```
$ jekyll serve --incremental
Configuration file: /Users/d/src/hyde/_config.yml
Configuration file: /Users/d/src/hyde/_config.yml
       Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
            Source: /Users/d/src/hyde
       Destination: /Users/d/src/hyde/_site
 Incremental build: enabled
      Generating...
Since v3.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Check https://jekyllrb.com/docs/upgrading/ for more info.
```

**Comment by ishu3101** [comment]
I was getting the same error. Manage to fix it with the following.

Remove `relative_permalinks: true` and add `gem: [jekyll-paginate, jekyll-gists]` to your **_config.yml** file

Now install the required gems using.

```
gem install jekyll-paginate
gem install jekyll-gist
```

**Comment by apbarraza** [comment]
None of these solutions worked for me. 

bundle exec jekyll serve 

indicates:
Could not locate Gemfile or .bundle/ directory

bundle update --bundler

indicates:
Could not locate Gemfile

**Comment by ram-ch** [comment]
None of the above solutions are working
