### ISSUE TITLE
Google+ comments messes up website width

### ISSUE THREAD

**Issue by fredrikaverpil** [poole/hyde#119]
I just added Google+ comments to my Hyde-based blog:

```
<!-- Google comments -->
<script src="https://apis.google.com/js/plusone.js">
</script>
<div class="g-comments"
  data-href="{{ site.url }}/{{  page.url }}"
  data-width="720"
  data-first_party_property="BLOGGER"
  data-view_type="FILTERED_POSTMOD">
</div>
```

However, turns out that this sets the width of the website somehow, to whatever `data-width` is in the code above.

Especially on low resolutions (mobile devices), this messes things up if you pinch and zoom out on a touch device such as the iPhone. Here's an [example post](http://fredrikaverpil.github.io/2012/02/06/whats-jekyll//):

![iPhone screenshot](https://lh3.googleusercontent.com/xmlp0d08OTePNHhfTFHpBO6U0TQorgdT8JoGFRmjqjB6IWj5I8_XIU3mY-17MtQveKSWUZ87Qe3gMZAW7PupT216k51kMZzf3cp_kpiVC6SyBNNLtsHsFPYvCRvDdfemw5QqeRYelca9SmIhfXIo3RsGWHyY5BcXZ83ZT9MgVYzAxGCcvUISsU7FzkXA5EgpF6GCPbsEiWi73OVWZVaTTHj7-pyszkMwdve3RWBumBpivZBQ6XtFLxMkBCG4PzRssSfu7VvgHsNE_8iS406p84Zi-sv9n7Uj7WtYDSqgCEgk9yxREuzx5fOTeWozdHO7LmWU5r1FqV8qOIbiwcrwEnePYgOcltpoklZ07Ghumc8ccrwwo3SAPmb07Bljcr7QR7ScquhDnNy4bMEJ9ynCIOkAt6oO1nZA_bqvfAoiU6Ry-kHqmIlIXtPN-Sb2meeMGB2xr7gPsgwI31r5-Bd-DItZN3IHfCrJjYIbmqJkrHcKt60ynq4Fh1eGPCJz5cJsSBBlZohE7m-gGNL1X-TkXlkurPlJ3MtoDMJL2PzO9EK6=w384-h680-no)

Please note, you won't see this on a desktop/laptop machine unless you make your browser window less than 720 pixels wide.

Now, I'm wondering if there's anything we could do about it, or if the issue lies within Google's code.

Any ideas?

**Comment by ghost** [comment]
It looks like the width is being set to 720 pixels via the element's style attribute. Playing around with the example page, you can remove the style and shrink it a little, but not enough to fit within the page without scrolling.

I'd see if there is something with their comments settings that can be enabled for mobile friendly.
