### ISSUE TITLE
Sidebar content inaccessible

### ISSUE THREAD

**Issue by henrywright** [poole/hyde#121]
If I add lots of links to the sidebar, some of them become inaccessible. See this screenshot (note Link 1 and Link 2 are cut off at the top).

![screenshot 2015-12-03 at 19 18 42](https://cloud.githubusercontent.com/assets/1963288/11571168/ee4c5434-99f2-11e5-8d73-3fe862005d41.png)

**Comment by ghost** [comment]
#103, #106 cover this. Either don't put a ton of links in the sidebar, or remove `.sidebar-sticky` to make it scroll with the page. That or you could do some `overflow-y: scroll` weirdness.

**Comment by henrywright** [comment]
I'm not sure removing sidebar sticky would result in a scrolling sidebar. I think that'd just stop the sidebar content from being affixed to the bottom.

Edit: But of course as you mention `overflow-y: scroll` will get the sidebar scrolling.
