### ISSUE TITLE
Move blog from Home to Page

### ISSUE THREAD

**Issue by aosavi** [poole/hyde#124]
The blog is by default situated at the home page (index.html). However, I'd like to make the home page a static page, and move the blog to a page (with page layout). How can this be done?

I run into 2 problems:
- When adding a new static index.html (layout: default), the title can't be changed (remains Home).
- When I rename the original index.html to for instance blog.html and set its layout to page, the blog is indeed shown as a page but it no longer shows the posts.

**Comment by mdo** [comment]
Take a look at the Jekyll docs for that—it should provide a bit more guidance. That said, you should be able to copy-paste the posts loop from the index page to any other page to provide a list of posts.

**Comment by aosavi** [comment]
Thanks. For future reference: if you run into the same problem you can indeed copy-paste the posts loop into the desired page, set the layout to default rather than page, and additionally manually add the page to the sidebar (see for instance 08fe7de43d71067eedda63eef0f78b689129addb line 29).
