### ISSUE TITLE
double home links on sidebar

### ISSUE THREAD

**Issue by nidegen** [poole/hyde#125]
If I have a non-blog main page, with index.html that way:

```

---
layout: page
title: Welcome

---
```

jekyll will produces two links in the sidebar to index.html: one called Home and one called Welcome (as desirted)

the only way i figured to not make two links is by commenting the title

```

---
layout: page
#title: Welcome

---
```

that way, but it leaves the main page without actual title... any help? thanks!

**Comment by JuanjoSalvador** [comment]
Did you tried to create custom layout...?
