### ISSUE TITLE
Can I use this theme with Jekyll 3.x?

### ISSUE THREAD

**Issue by pmalek** [poole/hyde#133]
I have just tried to use this theme with Jekyll 3.x and I can see that the posts are not displayed:

![selection_001](https://cloud.githubusercontent.com/assets/739996/13060296/a3f06344-d430-11e5-842c-46227bf10feb.png)

I have simply cloned https://github.com/poole/hyde/ and removed the following lines from `_config.xml`

```
relative_permalinks: true
paginate:         5
```

Is this theme compatible with Jekyll 3.x? Am I missing something?

**Comment by jjwesner** [comment]
comment out the relative links
-relative_permalinks: true
 +#relative_permalinks: true

**Comment by pmalek** [comment]
Ok, so I needed to add this to my `_config.xml`

```
gems: [jekyll-paginate, jekyll-gist]
```

and install those plugins since jekyll 3.x doesn't have them anymore (you have to install them manually). Now it works :)
