### ISSUE TITLE
Many elements are not displaying

### ISSUE THREAD

**Issue by HarvestingClouds** [poole/hyde#149]
I am trying to use Hyde theme but when I build it using Jekyll the Title, description, version no. etc. are missing. Also, the posts do not load in the right pane and only the disabled buttons for Newer and Older are shown. The change I have made to the _config.yml is I added the below gems section to the top:
# gems

  gems:
- jekyll-paginate
- redcarpet
- jekyll-gist
- pygments.rb

Any pointers on how to fix this would be great.

Below is the Screenshot of the home page as I am seeing it:
![image](https://cloud.githubusercontent.com/assets/5864392/14189947/12653d90-f75e-11e5-8d94-05df1c4216ff.png)

**Comment by vlasy** [comment]
This hapenned to me when I was missing basic settings (title, author, paginate,...) in `_config.yml`

**Comment by HarvestingClouds** [comment]
This was corrected with configurations, I forgot to close this issue. Thanks for your response @vlasy
