### ISSUE TITLE
Updated/maintained fork of Hyde ?

### ISSUE THREAD

**Issue by ameerdevs** [poole/hyde#167]
Judging by the latest commit date, pull requests and issues - this hasn't been updated in a while.
Can anyone recommend a stable updated fork of Hyde ?

I came across JuanjoSalvador/hyde for example @JuanjoSalvador

Thanks

**Comment by JuanjoSalvador** [comment]
I'm afraid of @mdo won't update Hyde anymore. Feel free to use my fork, it has some fixes for Jekyll 3.x in the `_config.yml`, but it needs some dependencies, like `jekyll-paginate`.

I'm using this changes into my website, and it works fine :)

https://github.com/JuanjoSalvador/hyde

**Comment by mdo** [comment]
I'll get to it eventually, but I have no plans to retire it. Plenty of PRs I need to get through across the board for this and all the other Poole themes. Focused on GitHub and the next Bootstrap alpha first though.

**Comment by amard33p** [comment]
https://github.com/fongandrew/hydeout
