### ISSUE TITLE
[Suggestion] Can the sidebar be made collapsible for mobile screens by default?

### ISSUE THREAD

**Issue by varadgunjal** [poole/hyde#171]
Just a thought. I know one can just customize it easily with CSS3 media queries, but would probably be great if the contents of the sidebar / navbar could be bundled in and kept in a persistent header to ease navigation with a simple dropdown? With the default, I keep scrolling back to the top to go to another page on mobile.

I know using Lanyon might probably be a better way to go for me, but I just like the Hyde theme so much.

**Comment by mrichman** [comment]
+1

**Comment by Fitzroy87** [comment]
Has anyone successfully customised Hyde to implement the suggestion of the OP?

**Comment by cckelly** [comment]
+1

**Comment by YangXiaozhou** [comment]
+1

**Comment by mdo** [comment]
Collapsing will stay with Lanyon :).
