### ISSUE TITLE
Not compatible

### ISSUE THREAD

**Issue by mrprofessor** [poole/hyde#193]
# Got the following error

Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
            Source: /home/professor/Desktop/Mrprofessor.github.io
       Destination: /home/professor/Desktop/Mrprofessor.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 49): Unknown tag 'gist' in /home/professor/Desktop/Mrprofessor.github.io/_posts/2012-02-07-example-content.md

**Comment by alexmoras** [comment]
Don't know if you've fixed it yet but from what I understand it's a pretty simple fix.
Simply go to your config file and comment out the line that says `paginate: 5` and add this line at the bottom `gems: [jekyll-paginate]`.

Don't get me wrong, I'm by NO means any good at jekyll but it worked for me.
