### ISSUE TITLE
Provide Gemfile and list gems in `_config.yml`?

### ISSUE THREAD

**Issue by wrzasa** [poole/hyde#196]
If it is "just download and start the Jekyll server", so why there is no `Gemfile` to enable quick install of dependencies and why gems required by the theme are not listed in the `_config.yml`?

**Comment by avk** [comment]
Agreed. This was a line-by-line setup:

```
source "https://rubygems.org"

gem "jekyll"  
gem "jekyll-paginate"
gem "jekyll-gist"
gem "redcarpet"
gem "pygments.rb"
```
