### ISSUE TITLE
collapsible sidebar

### ISSUE THREAD

**Issue by fabiocosta0305** [poole/hyde#203]
Any chance for implementing a collapsible sidebar, at least after the 1st level?

**Comment by TGNYC** [comment]
Check out [Lanyon](http://lanyon.getpoole.com).

**Comment by fabiocosta0305** [comment]
I didn't made myself clear... What I wanted is a sidebar with drop-down for extra levels on it...

Like

Foo
|- Bar
|- Baz

And when you click in Foo, Bar and Baz got down.

It's possible?

**Comment by mdo** [comment]
Yup you want Lanyon.
