### ISSUE TITLE
CSS Path Error

### ISSUE THREAD

**Issue by antmarakis** [poole/hyde#204]
I noticed that css is no longer loaded properly on my blog. It seems that the path to the CSS is wrong (for example, it tries to load CSS from `/page2/public/css/poole.css` instead of `public/css/poole.css`).

In the console error below, I was on Page 2 and it tried to load CSS from the wrong path.

![error](https://user-images.githubusercontent.com/17463361/28491002-7546bf82-6ef0-11e7-8316-de78a1ab7d47.png)

Here is my github repo: https://github.com/MrDupin/MrDupin.github.io

I have made minimal changes to the fork (only adding posts and some minor edits in CSS and HTML). In my config file I believe I have correctly set the base url. Any ideas why this may be happening?

**Comment by nabsiddiqui** [comment]
I believe this is related to #54 and #144.  Did you try the changes suggested there?

**Comment by antmarakis** [comment]
This worked like a charm, thank you sir!
