### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by MaxShalom** [poole/hyde#216]
Trying to use Hyde on Github Pages but, it isn't working. As of now in my `_config.yml` file, all I have is 
```
remote_theme: poole/hyde
```
What can I be doing wrong?

You can see my repository at https://github.com/MaxShalom/BootstrapX. 
To host I'm using a custom domain: http://maxshalom.me/BootstrapX/

**Comment by camilolunacom** [comment]
GitHub Pages only accepts the plugins listed [here](https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/).

**Comment by eisen1990** [comment]
in _config.yml
`
url: "https://MaxShalom.github.io"
`
and you will create repository named MaxShalom.github.com.
So, Github could host **MaxShalom.github.io** to you. and you can use theme.
