### ISSUE TITLE
Site won't build from fork

### ISSUE THREAD

**Issue by loganripplinger** [poole/hyde#224]
https://github.com/barryclark/jekyll-now seemed to indicate that the site should work just from forking, but that does not seem to be the case. This probably isn't an issue and is intended I assume.

Under GitHub Pages in the settings it gives me this error,

"Your site is having problems building: Your site is using the relative_permalinks configuration option. This setting is deprecated as has been removed from the latest version of Jekyll. To ensure your site continues to build as expected, remove the option from your site's configuration and update any post or page permalinks to be absolute to the site root, not the parent folder. For more information, see https://help.github.com/articles/page-build-failed-relative-permalinks-configured/."

**Comment by loganripplinger** [comment]
Refer to https://github.com/poole/poole#usage on how to get this running.

**Comment by LKremer** [comment]
hyde appears to be dead for now, but there is an updated fork here:
http://jekyllthemes.org/themes/hydeout/

**Comment by mdo** [comment]
Fix inbound with #258.
