### ISSUE TITLE
List of posts?

### ISSUE THREAD

**Issue by danaugrs** [poole/hyde#226]
Is there a way to show a list of posts (without showing the full content of each post) ?

**Comment by rohitbommisetti** [comment]
Create an 'Archive.md' page -> add this: 

---
layout semicolon page
title semicolon All Posts
---

{% for post in site.posts %}
  * {{ post.date | date_to_string }} &raquo; [ {{ post.title }} ]({{ post.url }})
{% endfor %}

**Comment by danaugrs** [comment]
Cool - thanks!
