### ISSUE TITLE
Posts do not appear in the index.html file

### ISSUE THREAD

**Issue by PeterHdd** [poole/hyde#229]
For anyone cloning this repository and running it locally, the posts will not appear in the website. I have finally figured it out, solution is below:

First, for multiple posts to show in the website, you need to use a for loop(which is already added in the index.html file):

    {% for post in paginator.posts %}
      <div class="post">
         <h1 class="post-title">
              <a href="{{ post.url }}">
                     {{ post.title }}
             </a>
                 </h1>
         <span class="post-date">{{ post.date | date_to_string }}</span>
               {{ post.content }}
         </div>
         {% endfor %}`

Since jekyll 3.0[ deprecated pagination](https://jekyllrb.com/docs/upgrading/2-to-3/#dropped-dependencies), you wont see any post. So add the following in the `_config.yml`:-

`gems: [jekyll-paginate]` and the execute jekyll build, and later jekyll serve. All the posts will appear in the home page.

Another solution is to loop the list of all posts so use the following:
`{% for post in site.posts %}`

instead of:

`{% for post in paginator.posts %}`
and it will work also.

**Note: I wrote this post, so no one wastes alot of time figuring it out, I did not do a pull request because last merged pull request was in 2015**

**Comment by afry-siam** [comment]
An update from 2021, the actual line you need to include in `_config.yml` is this: 
```
plugins: [jekyll-paginate]
```
