### ISSUE TITLE
I want to add few gems to my gemfile,

### ISSUE THREAD

**Issue by ostwalprasad** [poole/hyde#243]
I want to add few gems to my gemfile, but there's no gemfile present in root. Should I create new one or am I missing something?

**Comment by qndev** [comment]
> I want to add few gems to my gemfile, but there's no gemfile present in root. Should I create new one or am I missing something?

To create a new Gemfile to list your project’s dependencies run:
```
bundle init
```
Since v3.0, permalinks for pages removed, remove line
```
relative_permalinks: true
```
Upgrading from 2.x to 3.x: https://jekyllrb.com/docs/upgrading/2-to-3/

[Here refined theme has been forked from Hyde](https://github.com/qndev/hyde/tree/refine)

**Comment by ostwalprasad** [comment]
Thanks
