### ISSUE TITLE
Failing to load CSS for my site

### ISSUE THREAD

**Issue by Anthonyphilftwplz** [poole/hyde#254]
I am failing to load the CSS for my site:

Getting this error message
Failed to load resource: the server responded with a status  styles.css:1  404 ()

Here is my link on html:  link rel="stylesheet" href="css/styles.css">

**Comment by Anthonyphilftwplz** [comment]
<link rel="stylesheet" href="css/styles.css">

**Comment by akashpalrecha** [comment]
Check out #213. It should solve your issue.

**Comment by mdo** [comment]
Duplicate of #206
