### ISSUE TITLE
Issue with building the about or any other page that I added

### ISSUE THREAD

**Issue by startup101** [poole/hyde#256]
![image](https://user-images.githubusercontent.com/60231510/77130749-66846980-6a16-11ea-830a-982d901afe73.png)

This is how it looks, I tried using the default Hyde repo before changing anything. I had to change the config file to compile: 
removed this line

relative_permalinks: true

Any ideas why?

**Comment by startup101** [comment]
Had to add this to fix it

== "/" | relative_url %

**Comment by clairehhw** [comment]
Hi! I have the same issue. Could you specify how you fixed the problem? Thanks!
