### ISSUE TITLE
Hamburger Mobile Menu

### ISSUE THREAD

**Issue by asifimtious** [poole/hyde#263]
How can I make a sticky "Hamburger Mobile Menu" for mobile devices?

**Comment by federicoricca** [comment]
Trying to get something similar myself, without much success at the moment, unfortunately. Any luck?

**Comment by mdo** [comment]
Try Hyde's sibling theme, Lanyon: https://lanyon.getpoole.com.

**Comment by federicoricca** [comment]
Hi, thank you for the very quick reply. I was actually trying to maintain the current hyde structure on mobile, but instead of showing the whole content of the sidebar, have maybe only the site title showing (possibly sticky) at the top, and a button to expand the full content.
