### ISSUE TITLE
Right side of page is empty 

### ISSUE THREAD

**Issue by connect2robiul** [poole/hyde#277]
How to fill all page 

![Screenshot from 2020-12-23 21-22-35](https://user-images.githubusercontent.com/1263093/103026511-2b930180-4565-11eb-9e57-a3a85c0d1141.png)

**Comment by mdo** [comment]
There's a fixed width on the content. You'll need to override that. This is a good place to start. https://github.com/poole/hyde/blob/7c7f7550898e081264d255ef429a134fb00c72a8/public/css/poole.css#L288-L294
