### ISSUE TITLE
How do I apply Hyde to my Jekyll blog

### ISSUE THREAD

**Issue by sr-murthy** [poole/hyde#66]
Hi 

I really like the Hyde theme and want to use it in my Jekyll blog which I have an initial version of [here] (https://sr-murthy.github.io).  There are bugs I'm working through but how I apply the Hyde theme to the blog - via a layouts file?

Your instructions are not clear in this respect.

Any help would be appreciated.

Sandeep

**Comment by mdo** [comment]
The steps to install are briefly outlined at https://github.com/poole/poole#2b-roll-your-own-jekyll-site. Basically, either fork the entire repo as your starting point for a Jekyll site, or copy-paste all the required Jekyll files listed.

**Comment by mdo** [comment]
I've never used the custom defaults, so I can't tell you much for that. You can specify custom layouts for individual pages and posts though via front matter.

```
---
layout: default
---
```

or...

```
---
layout: custom-layout
---
```

**Comment by sr-murthy** [comment]
Thanks.
