### ISSUE TITLE
(howto) customize sidebar mobile rendering further? 

### ISSUE THREAD

**Issue by gvoysey** [poole/hyde#76]
Is there a clever way to adjust the alignment in the sidebar divs to adjust when viewed on mobile? 

see [my site that uses hyde](http://gvoysey.github.io) for what i mean -- on mobile the headshot is rendered nicely (centered), but on desktop it's still centered and it'd look better if it was left-aligned with the rest of the title. 

I'm doing this by embedding some custom CSS into an <img> block in `/_includes/sidebar.html`: 

```
  <div class="container sidebar-sticky">
    <div class="sidebar-about">

      <img style="margin:0px auto;display:block" src="{{ site.baseurl }}headshot-2.jpg" alt="headshot"/>

      <h2>
        <a href="{{ site.baseurl }}">
          {{ site.title }}
        </a>
      </h2>
      <p class="lead">{{ site.description }}</p>
    </div>
```

This feels like a horrible hack.  Is there a better way?  

I have looked around a little to see how jekyll detects mobile devices (via user-agent?) and how I might address that with a Liquid `{%if ...}` , but this is mostly not my area of expertise, so i haven't found anything.

**Comment by mdo** [comment]
You'll probably want to add those styles to the CSS files instead of using inline styles. You can use the same styles you've applied there, but you'll want to nest them in a media query (in the CSS file) so that they only apply to the mobile views. For example:

```css
@media (min-width: 48em) {
  .sidebar-about img {
    /* styles here */
  }
}
```

**Comment by gvoysey** [comment]
got it.  you can see the changes i made in my tree [here](https://github.com/gvoysey/gvoysey.github.io/blob/c7e05356d4334282691ceb82325847d7deefdd0e/public/css/hyde.css#L74) . 

For whatever reason, the test seems backwards to me, but it renders as I desire so i don't really care! 

thanks for giving us a slick theme, it's much appreciated.
