### ISSUE TITLE
baseurl and links to articles

### ISSUE THREAD

**Issue by superzazu** [poole/hyde#77]
Hello,

I've been experiencing some problems with hyde: whether or not I change the "baseurl" in the config file, the links (article url + related posts + sidebar links) does not seem to change. (I used the last commit of hyde and I updated all my gems (including jekyll) before)
First, note that my baseurl is : /blog

I had to add :
- in sidebar.html : <a class="sidebar-nav-item{% if page.url == node.url %} active{% endif %}" href="{{ site.baseurl }}{{ node.url }}">{{ node.title }}</a> _(aded {{ site.baseurl }})_
- in post.html (line 17): <a href="{{ site.baseurl }}{{ post.url }}"> _(added {{ site.baseurl}} )_

(sidenote : I think it would be nice to have a full HTML5 page (the doctype and some metas are in HTML4)

**Comment by lzubiaur** [comment]
Same issues here. I also had to add {{ site.baseurl }} in index.html line 10 (post title href)

**Comment by mdo** [comment]
Fix coming in #258.
