### ISSUE TITLE
hyde.css resets on jekyll serve

### ISSUE THREAD

**Issue by lelliphan** [poole/hyde#83]
I am trying to modify the following file:

https://github.com/poole/hyde/blob/master/public/css/hyde.css

However, whenever I regenerate the static site via

```
bundle exec jekyll serve
```

the css file is regenerated/reset.

How do I stop this from happening?

**Comment by nicolasmccurdy** [comment]
Make sure that you're modifying the file inside of `public/css`, and not `_site/public.css`. When Jekyll builds a site (which `jekyll serve` does behind the scenes), it copies the output to `_site`. If you modify a file in `_site`, it will be reset whenever you run `jekyll serve`.

**Comment by lelliphan** [comment]
Thanks!
